apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nats
  namespace: kube-system
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      name: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      hostNetwork: true
      containers:
        - name: nats-server
          image: openland/nats:v1
          args: ['--routes=nats://<user>:<password>@<server1>:6222,nats://<user>:<password>@<server2>:6222,nats://<user>:<password>@<server3>:6222']
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          env:
            - name: NATS_USER
              value: <user>
            - name: NATS_PASSWORD
              value: <password>
